### ISSUE TITLE
Transferring Ownership

### ISSUE THREAD

**Issue by grimlock-** [grimlock-/HumbleHands#35]
Yo matt, you're going to have to delete your fork in order for me to transfer ownership since you can't have 2 repos with the same name associated with your account

**Comment by ShadeByTheSea** [comment]
@grimlock- my repo has been deleted.

**Comment by grimlock-** [comment]
ok, github's on it.
"This repository is being transferred to @shadethedemon."
I'll close the issue when the transfer is done

**Comment by grimlock-** [comment]
I used to github's contact page to ask what the typical wait time is for a transfer. I'll make another post when I hear back.

**Comment by grimlock-** [comment]
ok, trying again. I aborted the last transfer and we'll try again. I'm told it should only take about 10 minutes after you accept the transfer, so make a post after you accept

**Comment by grimlock-** [comment]
And here you are sir, this repo is yours to do with as you please.
